#!/bin/bash

set -e

source library

check_root

create_bridge
echo "Created bridge"

for i in $(seq 1 $NUM_NNS); do
    create_pair $i "10.0.0.$i/24"
    set_master "${VETH_HOST_PREFIX}$i"
    echo "Created and configured veth pair $i"
done

echo "Done!"
